ALTER TABLE stage_runs DROP COLUMN IF EXISTS log;
ALTER TABLE images DROP COLUMN IF EXISTS version;
ALTER TABLE releases DROP COLUMN IF EXISTS source_run_id;
ALTER TABLE releases DROP COLUMN IF EXISTS lane_id;
