apiVersion: v1
kind: Service
metadata:
  name: {{ include "paas.fullname" . }}
  labels: {{- include "paas.labels" . | nindent 4 }}
spec:
  selector: {{- include "paas.coreSelector" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
